require-stack-version: ">= 1.6"

resolver: nightly-2020-12-14

packages:
- examples

extra-deps:
- git: https://github.com/ucsd-progsys/liquidhaskell.git
  commit: 8f38ac994714df52670df4eb1a267b1929de32bb
  subdirs:
  - .
  - liquid-base
  - liquid-containers
  - liquid-ghc-prim
- git: https://github.com/ucsd-progsys/liquid-fixpoint.git
  commit: 6b09a63d7d6b0f65b781b6923430774c11877aed
- megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
